export const SCENARIOS = {
  js: [
    'const x = 0;',
    'let name = "world";',
    'if (x === 1) { return; }',
    'const fn = () => {};',
    'function add(a, b) { return a + b; }',
    'console.log("hello");',
    'const arr = [1, 2, 3];',
    'const obj = { key: "value" };',
    'for (let i = 0; i < 10; i++) {}',
    'import { foo } from "./bar.js";',
    'export default function main() {}',
    'const res = await fetch(url);',
    'throw new Error("failed");',
    'arr.filter(x => x > 0).map(x => x * 2);',
    'Object.keys(obj).forEach(k => {});',
    'const [a, b] = arr;',
    'const { id, name } = user;',
    'class Foo { constructor() {} }',
    'try { doSomething(); } catch (e) {}',
    '`Hello, ${name}!`',
  ],
  python: [
    'def foo(x):',
    '    return x * 2',
    'if __name__ == "__main__":',
    'x = [i for i in range(10)]',
    'with open("file.txt") as f:',
    'print(f"value = {x}")',
    'import os, sys',
    'class MyClass:',
    '    def __init__(self):',
    '        self.value = 0',
    'raise ValueError("invalid")',
    'result = {k: v for k, v in items}',
    'lambda x: x + 1',
    'assert x > 0, "x must be positive"',
    'from pathlib import Path',
    'os.path.join(base, "subdir")',
    'try:',
    '    pass',
    'except Exception as e:',
    '    print(e)',
  ],
  git: [
    'git status',
    'git add -A',
    'git commit -m "fix: update"',
    'git push origin main',
    'git pull --rebase',
    'git checkout -b feature/foo',
    'git merge --no-ff feature/foo',
    'git log --oneline -10',
    'git diff HEAD~1',
    'git stash pop',
    'git rebase -i HEAD~3',
    'git reset --soft HEAD~1',
    'git remote -v',
    'git fetch --prune',
    'git tag v1.0.0',
    'git cherry-pick abc1234',
    'git blame src/main.ts',
  ],
  html: [
    '<div class="container">',
    '<span id="title">Hello</span>',
    '<input type="text" placeholder="...">',
    '<button onclick="fn()">Click</button>',
    '<a href="/path">link</a>',
    '<img src="./img.png" alt="">',
    '<ul><li>item</li></ul>',
    '<!DOCTYPE html>',
    '<meta charset="UTF-8">',
    '<link rel="stylesheet" href="./style.css">',
    '<script type="module" src="./app.js"></script>',
    '<form action="/submit" method="post">',
    '<label for="id">Name</label>',
    '<p class="text-sm text-gray-500">',
    '<nav aria-label="main">',
  ],
};

// ジャンルから指定件数のスニペットをランダム選択して1つの文字列に結合
export function pickScenario(genre, count = 5) {
  const pool = SCENARIOS[genre] || SCENARIOS.js;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).join(' ');
}
